INSERT INTO `pais` (`nome`, `sigla`) VALUES
  ('Brasil', 'BR'),
  ('Afeganistão', 'AF'),
  ('Albânia, Republica da', 'AL'),
  ('Argélia', 'DZ'),
  ('Samoa Americana', 'AS'),
  ('Andorra', 'AD'),
  ('Angola', 'AO'),
  ('Anguilla', 'AI'),
  ('Antártida', 'AQ'),
  ('Antigua e Barbuda', 'AG'),
  ('Argentina', 'AR'),
  ('Armênia, Republica da', 'AM'),
  ('Aruba', 'AW'),
  ('Austrália', 'AU'),
  ('Áustria', 'AT'),
  ('Azerbaijão, Republica do', 'AZ'),
  ('Bahamas, Ilhas', 'BS'),
  ('Bahrein, Ilhas', 'BH'),
  ('Bangladesh', 'BD'),
  ('Barbados', 'BB'),
  ('Belarus, Republica da', 'BY'),
  ('Bélgica', 'BE'),
  ('Belize', 'BZ'),
  ('Benin', 'BJ'),
  ('Bermudas', 'BM'),
  ('Butão', 'BT'),
  ('Bolívia', 'BO'),
  ('Bósnia-herzegovina (Republica da)', 'BA'),
  ('Botsuana', 'BW'),
  ('Ilha Bouvet', 'BV'),
  ('Território Britânico do Oceano Indico', 'IO'),
  ('Brunei', 'BN'),
  ('Bulgária, Republica da', 'BG'),
  ('Burkina Faso', 'BF'),
  ('Burundi', 'BI'),
  ('Camboja', 'KH'),
  ('Camarões', 'CM'),
  ('Canada', 'CA'),
  ('Cabo Verde, Republica de', 'CV'),
  ('Cayman, Ilhas', 'KY'),
  ('Republica Centro-Africana', 'CF'),
  ('Chade', 'TD'),
  ('Chile', 'CL'),
  ('China, Republica Popular', 'CN'),
  ('Christmas, Ilha (Navidad)', 'CX'),
  ('Cocos(Keeling, Ilhas', 'CC'),
  ('Colômbia', 'CO'),
  ('Comores, Ilhas', 'KM'),
  ('Congo', 'CG'),
  ('Congo, Republica Democrática do', 'CD'),
  ('Cook, Ilhas', 'CK'),
  ('Costa Rica', 'CR'),
  ('Costa do Marfim', 'CI'),
  ('Croácia (Republica da)', 'HR'),
  ('Cuba', 'CU'),
  ('Chipre', 'CY'),
  ('Tcheca, Republica', 'CZ'),
  ('Dinamarca', 'DK'),
  ('Djibuti', 'DJ'),
  ('Dominica, Ilha', 'DM'),
  ('Republica Dominicana', 'DO'),
  ('Timor Leste', 'TL'),
  ('Equador', 'EC'),
  ('Egito', 'EG'),
  ('El Salvador', 'SV'),
  ('Guine-Equatorial', 'GQ'),
  ('Eritreia', 'ER'),
  ('Estônia, Republica da', 'EE'),
  ('Etiópia', 'ET'),
  ('Falkland (Ilhas Malvinas)', 'FK'),
  ('Feroe, Ilhas', 'FO'),
  ('Fiji', 'FJ'),
  ('Finlândia', 'FI'),
  ('Franca', 'FR'),
  ('Guiana francesa', 'GF'),
  ('Polinésia Francesa', 'PF'),
  ('Terras Austrais e Antárticas Francesas', 'TF'),
  ('Gabão', 'GA'),
  ('Gambia', 'GM'),
  ('Georgia, Republica da', 'GE'),
  ('Alemanha', 'DE'),
  ('Gana', 'GH'),
  ('Gibraltar', 'GI'),
  ('Grécia', 'GR'),
  ('Groenlândia', 'GL'),
  ('Granada', 'GD'),
  ('Guadalupe', 'GP'),
  ('Guam', 'GU'),
  ('Guatemala', 'GT'),
  ('Guine', 'GN'),
  ('Guine-Bissau', 'GW'),
  ('Guiana', 'GY'),
  ('Haiti', 'HT'),
  ('Ilha Heard e Ilhas McDonald', 'HM'),
  ('Vaticano, Estado da CidadeController do', 'VA'),
  ('Honduras', 'HN'),
  ('Hong Kong', 'HK'),
  ('Hungria, Republica da', 'HU'),
  ('Islândia', 'IS'),
  ('Índia', 'IN'),
  ('Indonésia', 'ID'),
  ('Ira, Republica Islâmica do', 'IR'),
  ('Iraque', 'IQ'),
  ('Irlanda', 'IE'),
  ('Israel', 'IL'),
  ('Itália', 'IT'),
  ('Jamaica', 'JM'),
  ('Japão', 'JP'),
  ('Jordânia', 'JO'),
  ('Cazaquistão, Republica do', 'KZ'),
  ('Quênia', 'KE'),
  ('Kiribati', 'KI'),
  ('Coreia, Republica Popular Democrática da', 'KP'),
  ('Coreia, Republica da', 'KR'),
  ('Coveite', 'KW'),
  ('Quirguiz, Republica', 'KG'),
  ('Laos, Republica Popular Democrática do', 'LA'),
  ('Letônia, Republica da', 'LV'),
  ('Líbano', 'LB'),
  ('Lesoto', 'LS'),
  ('Libéria', 'LR'),
  ('Líbia', 'LY'),
  ('Liechtenstein', 'LI'),
  ('Lituânia, Republica da', 'LT'),
  ('Luxemburgo', 'LU'),
  ('Macau', 'MO'),
  ('Macedônia, Antiga Republica Iugoslava', 'MK'),
  ('Madagascar', 'MG'),
  ('Malavi', 'MW'),
  ('Malásia', 'MY'),
  ('Maldivas', 'MV'),
  ('Mali', 'ML'),
  ('Malta', 'MT'),
  ('Marshall, Ilhas', 'MH'),
  ('Martinica', 'MQ'),
  ('Mauritânia', 'MR'),
  ('Mauricio', 'MU'),
  ('Mayotte (Ilhas Francesas)', 'YT'),
  ('México', 'MX'),
  ('Micronesia', 'FM'),
  ('Moldávia, Republica da', 'MD'),
  ('Mônaco', 'MC'),
  ('Mongólia', 'MN'),
  ('Montserrat, Ilhas', 'MS'),
  ('Marrocos', 'MA'),
  ('Moçambique', 'MZ'),
  ('Mianmar (Birmânia)', 'MM'),
  ('Namíbia', 'NA'),
  ('Nauru', 'NR'),
  ('Nepal', 'NP'),
  ('Países Baixos (Holanda)', 'NL'),
  ('Antilhas Holandesas', 'AN'),
  ('Nova Caledonia', 'NC'),
  ('Nova Zelândia', 'NZ'),
  ('Nicarágua', 'NI'),
  ('Níger', 'NE'),
  ('Nigéria', 'NG'),
  ('Niue, Ilha', 'NU'),
  ('Norfolk, Ilha', 'NF'),
  ('Marianas do Norte', 'MP'),
  ('Noruega', 'NO'),
  ('Oma', 'OM'),
  ('Paquistão', 'PK'),
  ('Palau', 'PW'),
  ('Panamá', 'PA'),
  ('Papua Nova Guine', 'PG'),
  ('Paraguai', 'PY'),
  ('Peru', 'PE'),
  ('Filipinas', 'PH'),
  ('Pitcairn, Ilha', 'PN'),
  ('Polônia, Republica da', 'PL'),
  ('Portugal', 'PT'),
  ('Porto Rico', 'PR'),
  ('Catar', 'QA'),
  ('Reunião, Ilha', 'RE'),
  ('Romênia', 'RO'),
  ('Rússia, Federação da', 'RU'),
  ('Ruanda', 'RW'),
  ('São Cristovão e Neves, Ilhas', 'KN'),
  ('Santa Lucia', 'LC'),
  ('São Vicente e Granadinas', 'VC'),
  ('Samoa', 'WS'),
  ('San Marino', 'SM'),
  ('São Tome e Príncipe, Ilhas', 'ST'),
  ('Arábia Saudita', 'SA'),
  ('Senegal', 'SN'),
  ('Seychelles', 'SC'),
  ('Serra Leoa', 'SL'),
  ('Cingapura', 'SG'),
  ('Eslovaca, Republica', 'SK'),
  ('Eslovênia, Republica da', 'SI'),
  ('Salomão, Ilhas', 'SB'),
  ('Somalia', 'SO'),
  ('África do Sul', 'ZA'),
  ('Ilhas Geórgia do Sul e Sandwich do Sul', 'GS'),
  ('Espanha', 'ES'),
  ('Sri Lanka', 'LK'),
  ('Santa Helena', 'SH'),
  ('São Pedro e Miquelon', 'PM'),
  ('Sudão', 'SD'),
  ('Suriname', 'SR'),
  ('Svalbard e Jan Mayen', 'SJ'),
  ('Suazilândia', 'SZ'),
  ('Suécia', 'SE'),
  ('Suíça', 'CH'),
  ('Síria, Republica Árabe da', 'SY'),
  ('Formosa (Taiwan)', 'TW'),
  ('Tadjiquistao, Republica do', 'TJ'),
  ('Tanzânia, Republica Unida da', 'TZ'),
  ('Tailândia', 'TH'),
  ('Togo', 'TG'),
  ('Toquelau, Ilhas', 'TK'),
  ('Tonga', 'TO'),
  ('Trinidad e Tobago', 'TT'),
  ('Tunísia', 'TN'),
  ('Turquia', 'TR'),
  ('Turcomenistão, Republica do', 'TM'),
  ('Turcas e Caicos, Ilhas', 'TC'),
  ('Tuvalu', 'TV'),
  ('Uganda', 'UG'),
  ('Ucrânia', 'UA'),
  ('Emirados Árabes Unidos', 'AE'),
  ('Reino Unido', 'GB'),
  ('Estados Unidos', 'US'),
  ('Ilhas Menores Distantes dos Estados Unidos', 'UM'),
  ('Uruguai', 'UY'),
  ('Uzbequistão, Republica do', 'UZ'),
  ('Vanuatu', 'VU'),
  ('Venezuela', 'VE'),
  ('Vietnã', 'VN'),
  ('Virgens, Ilhas (Britânicas)', 'VG'),
  ('Virgens, Ilhas (E.U.A.)', 'VI'),
  ('Wallis e Futuna, Ilhas', 'WF'),
  ('Saara Ocidental', 'EH'),
  ('Iémen', 'YE'),
  ('Iugoslávia, República Fed. da', 'YU'),
  ('Zâmbia', 'ZM'),
  ('Zimbabue', 'ZW'),
  ('Guernsey, Ilha do Canal (Inclui Alderney e Sark)', 'GG'),
  ('Jersey, Ilha do Canal', 'JE'),
  ('Canarias, Ilhas', NULL),
  ('Man, Ilha de', 'IM'),
  ('Johnston, Ilhas', NULL),
  ('Madeira, Ilha da', NULL),
  ('Montenegro', 'ME'),
  ('Republika Srbija', 'RS'),
  ('Sudao do Sul', 'SS'),
  ('Zona do Canal do Panamá', NULL),
  ('Wake, Ilha', NULL),
  ('Lebuan, Ilhas', NULL),
  ('Palestina', 'PS'),
  ('Ilhas de Aland', 'AX'),
  ('Coletividade de São Bartolomeu', 'BL'),
  ('Curaçao', 'CW'),
  ('Ilha de São Martinho (França)', 'MF'),
  ('São Martinho (Países Baixos)', 'SX');